EXPERIMENT:
  NAME: ""
  TAG: "crd,res50,mobilenetv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "CRD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd" 
CRD:
  FEAT:
    STUDENT_DIM: 1024
    TEACHER_DIM: 2048
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
