EXPERIMENT:
  NAME: ""
  TAG: "kd,dot,r18,shuv2"
  PROJECT: "dot_tinyimagenet"
DATASET:
  TYPE: "tiny_imagenet"
  NUM_WORKERS: 16
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet18"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 200
  LR: 0.2
  LR_DECAY_STAGES: [60, 120, 160]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "dot"
  DOT:
    DELTA: 0.075
