EXPERIMENT:
  NAME: ""
  TAG: "at,res50,mobilenetv2"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "AT"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
