EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,res50,mobilenetv2"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
REVIEWKD:
  CE_WEIGHT: 1.0
  REVIEWKD_WEIGHT: 8.0
  WARMUP_EPOCHS: 1
  SHAPES: [1,7,14,28,56]
  OUT_SHAPES: [1,7,14,28,56]
  IN_CHANNELS: [128,256,512,1024,1024]
  OUT_CHANNELS: [256,512,1024,2048,2048]
  MAX_MID_CHANNEL: 256
  STU_PREACT: True
